### ISSUE TITLE
Adding visual effect for tree map box

### ISSUE THREAD

**Issue by raashika03** [edamontology/edam-browser#69] opened 2021-04-01 12:20 UTC
adding a resize feature in the tree map box will be a good idea I think, cause while scrolling through the browser in smaller screens like in phone, tree map box acquires almost the whole screen leaving some spaces below and above it, and only those spaces can be used for scrolling which makes it difficult for the user to scroll down or up.
![IMG_20210401_173607](https://user-images.githubusercontent.com/45493793/113291610-e4a96a80-9310-11eb-818a-f9a87be0da27.jpg)
Only red area marked can be used for scrolling down, which seems frustrating, I felt this when I used Edam browser in the phone for the first time, 
I thought my phone isn't working :( took me few minutes to realise that box isn't scrollable like other elements. Even scrolling using vertical scrollbar isn't at all feasible in phone at least because of its less width by default.
 

So a decrease option to minimise the box size( not to zero)  will be nice.

1) It can be done something similar to what's there for applications in an os, Resizing using cursor at the corners. 
![images](https://user-images.githubusercontent.com/45493793/113292041-8cbf3380-9311-11eb-80bd-3a51989580ff.png)

2) Another way can be to provide a button kind of thing like in some PDF reader to change size to 50%, 100%, 10%... For the tree map box only. 
![IMG_20210401_174557](https://user-images.githubusercontent.com/45493793/113292545-4918f980-9312-11eb-95d1-8fe6235ea8e7.jpg)

I think 1 will work in desktop version only, so option 2 can be used which will be made to appear for screens of size less than a particular value. 

Refreshing is also difficult currently.

What are your views @bryan-brancotte @matuskalas @hmenager :-)

**Comment by raashika03** [comment] 2021-04-01 13:36
![Screenshot_2021-04-01-18-52-26-64](https://user-images.githubusercontent.com/45493793/113300375-7a49f780-931b-11eb-8bba-4993dc82c46f.png)
I just noticed that, This feature is really important for smaller screens, because when you zoom out the tree map once (using points at both those red areas Simulataneously, just by two fingers)
![IMG_20210401_190415](https://user-images.githubusercontent.com/45493793/113301869-19232380-931d-11eb-9c31-59ccfdc5bd45.jpg)
 then there's no go back to the scroll option easily unless you press back button in the phone.
So a soln might be the availability of option 2 on the screen , visibility only for smaller screens.
Try it out, you'll understand the need :-P

**Comment by bryan-brancotte** [comment] 2021-04-01 13:48
Hi @raashika03 

I understand the frustration, that why I reduce the size of the tree to not 100% of the view height, so we can grab after the tree. Still, your point is valid as we do not know when dragging inside the tree that we are not dragging the page but the tree ... which doesn't move as not zoomed enough :/

I understand your solution but I think this issue could be solve in an other way:
![border-on-move](https://user-images.githubusercontent.com/11556772/113302243-27167b80-9300-11eb-8055-89ace8e28749.gif)
In this example you see that the border changes to black when we drag/scroll inside the tree, while is grey when scroll/drag/zoom outside the tree. The border might not be the best visual solution, but I think we should visually inform the user that only the tree is affected when scrolling inside.

P.S: I agree that if we zoom so the whole viewed area is the tree then we cannot escape it, the buttons would not solve the issue completely as if they are not visible at this moment we are still trapped.

**Comment by raashika03** [comment] 2021-04-01 14:16
>
>I understand the frustration, that why I reduce the size of the tree to not 100% of the view height, so we can grab after the tree.

But This's not so much useful for size of normal android screen. 
>
> I understand your solution but I think this issue could be solve in an other way:
> ![border-on-move](https://user-images.githubusercontent.com/11556772/113302243-27167b80-9300-11eb-8055-89ace8e28749.gif)
> In this example you see that the border changes to black when we drag/scroll inside the tree, while is grey when scroll/drag/zoom outside the tree. The border might not be the best visual solution, but I think we should visually inform the user that only the tree is affected when scrolling inside.

But this visual effect is not available for Android phone size reason may be a limit on that effect to a particular size only. 
![Screenshot_2021-04-01-19-36-34-35](https://user-images.githubusercontent.com/45493793/113306329-99e41e80-9321-11eb-8097-8bae7559b60f.png)
So visual effect generation for this size will solve this problem at least.

> 
> P.S: I agree that if we zoom so the whole viewed area is the tree then we cannot escape it, the buttons would not solve the issue completely as if they are not visible at this moment we are still trapped.

What if some pop up option is generated for the size (of the visual screen) smaller than a particular value which'll will appear when tree map box size>= visual screen size. I think this should do the work. This pop up option can be generated in the visual screen for the above '>=' condition Ig.

**Comment by bryan-brancotte** [comment] 2021-04-01 14:24
I wasn't very clear about the border effect I showed in the animation sorry, it is something that is for now not available but could be implemented by you, and would then be available on any screen/os. Implementing such effect would also allow you to dive into the code of the tree, and find where to add the listeners.

**Comment by raashika03** [comment] 2021-04-01 14:29
> I wasn't very clear about the border effect I showed in the animation sorry, it is something that is for now not available but could be implemented by you, and would then be available on any screen/os. 

OK I'll implement this. 
>
>Implementing such effect would also allow you to dive into the code of the tree, and find where to add the listeners.

What does listeners means here? Are you linking with screen reader thing(out of box:/)?

**Comment by bryan-brancotte** [comment] 2021-04-01 14:37
I did not understood your second question, but to answer the first I was talking about listener in the d3js code.

**Comment by raashika03** [comment] 2021-04-01 14:46
>
> I did not understood your second question, 

I understood second one too by your answer to first.
>
>but to answer the first I was talking about listener in the d3js code.
Ok👍

**Comment by matuskalas** [comment] 2021-04-01 22:34
Thank you sooo much @raashika03 & @bryan-brancotte for diving into the details of this usability issue! 🚀

As @bryan-brancotte suggested, it will indeed be very nice if you, @raashika03 work on the implementation with help of @bryan-brancotte's suggestions. I'm assigning it and looking forward!

**Comment by bryan-brancotte** [comment] 2021-04-13 12:07
A first attempt with pure css have been tried in #95 but does not do the trick. As far as I know there is no solution without javascript.

**Comment by raashika03** [comment] 2021-04-13 12:11
Oki @bryan-brancotte I'll now go for listeners.

**Comment by HagerDakroury** [comment] 2021-05-26 08:48
I guess this is now a duplicate of #201 ? The issue now is to make the resizer work on mobile, right? Or the visual effect is still a desired feature? @bryan-brancotte

**Closed** 2021-05-26 11:01 UTC
Labels: new feature, ux/ui design
