### ISSUE TITLE
[enhancement] Error handling 

### ISSUE THREAD

**Issue by tawahpeggy** [edamontology/edam-browser#133] opened 2021-04-17 10:31 UTC
when a service is down or something isn't working, its really necessary and important  to let the users know rather than keeping them in the dark, and this is done by adding messages to be seen incase of certain errors but thats not the case as of now. i noticed especially when trying to load t a custom ontology if something goes wrong, the modal disappears instead of showing some hints why it failed but opening the dev console errors can be seen which should be relayed to the user for good user experience.

**Comment by tawahpeggy** [comment] 2021-04-17 10:32
Also when a process is successful, it's nice to let the user know its been successfully carried out while displaying the result

**Comment by bryan-brancotte** [comment] 2021-04-27 02:19
Hi @tawahpeggy 

I see that  #137 is a duplicate of this issue, normally the older issue is kept open but as a conversation already took place in #137 I will close #133 and mention it there.

Also note that having a short and precise title issue help other dev to not miss you issue, in this case `[enhancement]` is not needed as maintainers can later add the label (I just did for the example), and `Error handling` is too vague, `Error handling on custom ontology loading` would maybe have help matuskalas or secrashi to see this issue.

**Closed by bryan-brancotte** 2021-04-27 02:19 UTC
Labels: enhancement
