### ISSUE TITLE
[enhancement] fix full tree not shown when many nodes are open

### ISSUE THREAD

**Issue by tawahpeggy** [edamontology/edam-browser#138] opened 2021-04-22 00:56 UTC
when too many  nodes are open, some content is hidden so I am thinking of adding something like a scrollable so users can scroll and see any angle of the tree @all please what are your suggestions?

**Comment by HagerDakroury** [comment] 2021-04-22 09:12
Hi @tawahpeggy, This is the same issue as #79. You'll find it well documented and discussed there. It also addresses the same issue when zooming.

**Comment by tawahpeggy** [comment] 2021-04-23 04:58
okay @HagerDakroury  thanks for your feedback

**Comment by bryan-brancotte** [comment] 2021-04-26 21:27
Hi, indeed quite a duplicate of #79, closing current issue in favor of #79

**Closed by bryan-brancotte** 2021-04-26 21:27 UTC
