### ISSUE TITLE
Tree cropped when zooming in

### ISSUE THREAD

**Issue by pooja2299** [edamontology/edam-browser#79] opened 2021-04-04 17:04 UTC
It is difficult to navigate when more than one tree is expanded. 
![image](https://user-images.githubusercontent.com/44069818/113514202-ebdbad00-958a-11eb-93f0-0f41f12f04d7.png)

Also, when trying to scroll to other branches, the image gets cropped when zoomed in.
Steps to reproduce the problem :
Go to 
![image](https://user-images.githubusercontent.com/44069818/113515051-bc7b6f00-958f-11eb-9b08-375d56617d2c.png)

![image](https://user-images.githubusercontent.com/44069818/113515063-d6b54d00-958f-11eb-8299-a3b1d0a5b48a.png)

I would like to suggest to add scrollbar both horizontal and vertical. Something like this:

![image](https://user-images.githubusercontent.com/44069818/113515758-12eaac80-9594-11eb-9fae-859f04d6e4b3.png)

This would allow user to navigate to all the branches when in zoom in mode.
 
Woul like to have your suggestions @hmenager @bryan-brancotte @matuskalas

**Comment by raashika03** [comment] 2021-04-04 17:21
This's much needed :100: @pooja2299 
BTW @mentors why browser doesn't sets a scrollbar itself here? Generally they do set themselves when content is more than the visible screen. Is this feature purposely hidden here?

**Comment by pooja2299** [comment] 2021-04-04 17:43
Don't know. No idea :sweat_smile:

**Comment by raashika03** [comment] 2021-04-04 19:47
> Don't know. No idea

I got the answer overflow property defined in CSS is not widely implemented yet and that tree map box is an svg element and for svg I think it has some part yet left to be implemented to set scrollbar for overflow by itself [Source](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/overflow), So you can add manually for that :) 

Hey @pooja2299 the image is movable but on double clicking (this's not known to user as there's no indication kind of thing), So may be scroll bar won't be needed but for better user experience  it should be included I think. When scroll bar will be added then this will be more explicit that image can be moved here and there.

**Comment by pooja2299** [comment] 2021-04-04 19:58
Thanks @raashika03 for the solution.



> Hey @pooja2299 the image is movable but on double clicking (this's not known to user as there's no indication kind of thing), So may be scroll bar won't be needed but for better user experience it should be included I think. When scroll bar will be added then this will be more explicit that image can be moved here and there.

Yes it is movable but some of the right and left portion of the image can not be scrolled further after certain point. 
For example, when I zoomed this in mobile view and scrolled horizontally , it was not scrolling till the edam node in the leftmost of the tree. 
![WhatsApp Image 2021-04-04 at 21 42 17](https://user-images.githubusercontent.com/44069818/113520067-3d496380-95ae-11eb-8754-8d7e5f50336b.jpeg)

**Comment by raashika03** [comment] 2021-04-04 20:09
Yes I just noticed, so adding scroll bar is the only viable solution it seems :) :100:

**Comment by bryan-brancotte** [comment] 2021-04-08 10:34
Hi @pooja2299 

Indeed the view can be improved, it is not pleasant to have the tree cropped. Scrollbar is not the only viable solution. 

To work on this issue one should first explore the usage of the tree and the pan and zoom, and see if any boundary are set and if they can be improved. Scrollbar could be added, but one should first evaluate if current solution can be fixed before adding new functionality.

**Comment by pooja2299** [comment] 2021-04-08 12:59
Ok @bryan-brancotte . Will look into it :+1:

**Comment by secrashi** [comment] 2021-04-13 09:27
Hey, @pooja2299, I too came across a similar problem regarding the positioning of the tree. When I open a particular field say operations from the drop-down menu, it loads like this
![WhatsApp Image 2021-04-13 at 2 41 56 PM](https://user-images.githubusercontent.com/56053777/114529393-8745df80-9c67-11eb-9d09-f522f7734794.jpeg)

Though these are not exactly similar issues their solutions might be linked to each other. One way of solving my problem would be making some changes in translate and transform properties in CSS, though it wouldn't fully solve your issue. Do you have any other viable solution to the problem?

**Comment by HagerDakroury** [comment] 2021-04-13 15:34
> Hey, @pooja2299, I too came across a similar problem regarding the positioning of the tree. When I open a particular field say operations from the drop-down menu, it loads like this
> ![WhatsApp Image 2021-04-13 at 2 41 56 PM](https://user-images.githubusercontent.com/56053777/114529393-8745df80-9c67-11eb-9d09-f522f7734794.jpeg)
> 
> Though these are not exactly similar issues their solutions might be linked to each other. One way of solving my problem would be making some changes in translate and transform properties in CSS, though it wouldn't fully solve your issue. Do you have any other viable solution to the problem?

Hi @secrashi, I have a question regarding this behavior.

Have you tried moving it? (does it move or remains cropped?) I tried reproducing this from a PC and as soon as I touch the tree, the position is fixed.

Let me know!

**Comment by secrashi** [comment] 2021-04-16 06:08
Hey @HagerDakroury, Yes the position gets fixed when I touch the tree, but by default, it appears cropped!

**Comment by HagerDakroury** [comment] 2021-06-16 13:56
@bryan-brancotte, should this be closed? I can't reproduce it anymore. I think it got fixed with #115

**Comment by bryan-brancotte** [comment] 2021-06-16 15:32
I agree with you @HagerDakroury

**Closed by bryan-brancotte** 2021-06-16 15:32 UTC
Labels: enhancement
