### ISSUE TITLE
Pointer-event on the node names

### ISSUE THREAD

**Issue by pooja2299** [edamontology/edam-browser#135] opened 2021-04-18 21:32 UTC
The mouse pointer when hovered over the labels of the nodes, appears as shown in the pic below. This could be because all the names of nodes are of type 'text'.
I would like to do a small change to mouse pointer. It should not show the pointer as shown in the pic.

![image](https://user-images.githubusercontent.com/44069818/115161426-30069b80-a0bb-11eb-8103-38ead21f6b05.png)

 Rather, should show normal mouse pointer when hovered over the names of the node like this:  
![image](https://user-images.githubusercontent.com/44069818/115161488-883d9d80-a0bb-11eb-9e20-3d7851df5ca8.png)

**Comment by pooja2299** [comment] 2021-04-18 21:38
I was trying to achieve this by editing the tree-reusable-d3.css file. But it was showing no changes. My code
`.node text{
     pointer-events : none;}`

Even any chnage any where else in this file is not shown on the website. For eg: I tries to change the font-size of the text of the nodes but no changes were shown. What could be the possible reason for it? 
Can anyone help me with this?

**Comment by pooja2299** [comment] 2021-04-18 21:45
Its working now after re-running  the start_edam_stand_alone_browser.sh file again :smile: . Maybe some cache problem. 
Thank you.

**Comment by HagerDakroury** [comment] 2021-04-19 09:09
Hi @pooja2299 , this is a duplicate of #90. There's also a PR for that.

**Comment by pooja2299** [comment] 2021-04-19 09:31
Oh sorry, I didnt notice.  Thanks @HagerDakroury

**Comment by bryan-brancotte** [comment] 2021-04-27 02:12
Hi @pooja2299 

As indicated by HagerDakroury it is a duplicate so I'm closing this issue (also now fixed).

**Closed** 2021-04-27 02:11 UTC
