### ISSUE TITLE
Enhancing the UI of URI.

### ISSUE THREAD

**Issue by secrashi** [edamontology/edam-browser#82] opened 2021-04-05 04:26 UTC
**Problem:** The link's UI looks distorted when the tab is resized.

![IMG_20210405_094655](https://user-images.githubusercontent.com/56053777/113536894-d1d6b480-95f4-11eb-9e5c-874244adc883.jpg)

**Proposed Solution:** Instead of continuing the link to the next line, We can make the extra characters hide in the blue box itself, and add a scroll bar at the bottom of the blue box, so we can scroll to the right and see the whole link. That is, I want to make the link box responsive.

**Comment by raashika03** [comment] 2021-04-05 05:11
[Just a suggestion] This condition occurs for a very small range of screen for all the types(edam, data, format.... I checked for all), so if you're going to create a scroll bar for the same then remember to make them visible in only that range (this happens if chrome creates scroll bar itself, but since you're gonna add up so you'll have to take care of this) other wise this will unnecessarily add up in other screen sizes.
Because when the screen size is further reduced after a limit then the term table aligns itself at the bottom of the tree map box, so again URI value appears in a single line only 

Only for this range of screen sizes, this condition occurs: 

![Screenshot from 2021-04-05 10-31-39](https://user-images.githubusercontent.com/45493793/113539247-f9c91680-95fa-11eb-87fa-37232e4a47a9.png)
![Screenshot from 2021-04-05 10-31-24](https://user-images.githubusercontent.com/45493793/113539255-ff266100-95fa-11eb-8b50-338bdc3da204.png)

**Comment by secrashi** [comment] 2021-04-05 06:04
Yeah, I noticed that It's only for a small range. I thought of adding the scroll bar so that a user can easily copy it, but recently I checked that someone has added an issue of adding a copy button next to URI. If that happens there is no need for a scroll bar and we can simply hide the content instead of continuing it on the next line or using a scroll bar. That is set overflow property to hidden.

**Comment by raashika03** [comment] 2021-04-05 06:18
I think now @mentors suggestions is needed that whether they would like have that copy button(this's better from design perspective) (someone is already working on this, so may be they'll go with this) or scroll bar kind of thing.
Just asking, will hiding enable to copy the whole link? If it won't let, then there's no point of hiding, better to leave this as it's (in continuation on next line).

**Comment by matuskalas** [comment] 2021-04-05 12:30
Thanks a lot @secrashi & @raashika03 for diving into this issue, documenting it so well, and discussing the possible solutions!!! 👍🏽
I'd say:
 - Indeed, we want a copy-URI button there (#40)
 - I fully agree with you that the wrapped URI is not pretty
 - But maybe it is still less bad than making the whole panel scrollable? (all the other fields seem to wrap nicely)
 - If you insist it's not good enough that it wraps to a new line, then for a complex solution, what would you think about these options? Of course, they would be visual compromises ...:
     - Scaling down the URI (+the copy-URI button which will be next to it)
     - Narrowing the cell with the label **URI** (either that single cell, or the whole column)

**Comment by secrashi** [comment] 2021-04-06 02:04
Thanks for pointing them out @matuskalas. Instead of compromising the visuals of the website, we can do this:
- Make the word URI on the left-side clickable. i.e. we can reach the link by clicking on word URI.
- Instead of writing down the link on the right side, we can just make a copy URI button there. 
Pros: 
- It will make the UI look good. 
- UX will improve.
Cons:
- Full link will not be visible.

**Comment by bryan-brancotte** [comment] 2021-04-08 10:00
Hi @secrashi 

Thanks for your interest, indeed the URI rendering as it is now is not perfect, far from it ! That is part of the point of #40, and you brought a new aspect for this issue. I recommend that we continu this discussion in #40 in order to have the best ideas on all aspect (clickable AND render) in one issue, and thus closing it as a partial duplicate of #40.

**Closed by bryan-brancotte** 2021-04-08 10:00 UTC
Labels: help wanted, question, ux/ui design
